[package]
name = "callgrind_differ"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "A tool to compare outputs of `callgrind_annotate` over time. "
categories = [ "command-line-utilities", "development-tools::profiling" ]
repository = "https://github.com/Ethiraric/callgrind_differ"
readme = "README.md"

[dependencies]
anyhow = { version = "1.0.79", features = ["backtrace"] }
clap = { version = "4.5.3", features = ["derive"] }
itertools = "0.12.1"
